# Generated by Django 3.2 on 2021-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('address', models.CharField(max_length=150, verbose_name='Company Address')),
                ('location', models.CharField(max_length=100, verbose_name='Company Location')),
                ('mobile_phone', models.CharField(max_length=12, verbose_name='Mobile Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('website', models.URLField(verbose_name='Company website')),
                ('identification_number', models.CharField(max_length=11, verbose_name='Company identification number')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
    ]
