# Generated by Django 3.2 on 2021-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_number',
            field=models.CharField(max_length=11, verbose_name='პირადი ნომერი'),
        ),
    ]
