# Generated by Django 3.2 on 2021-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ბუღალტერი'), (2, 'დიზაინერი'), (3, 'მენეჯერი'), (4, 'ქოლ ცენტრი')], null=True),
        ),
    ]
