# Generated by Django 3.2 on 2021-04-14 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='სახელი')),
                ('alias', models.CharField(max_length=10, verbose_name='ალიასი')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='პროდუქტის დასახელება')),
                ('alias', models.CharField(max_length=10, verbose_name='ალიასი')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='ლარი', max_digits=5, verbose_name='ფასი')),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='ლარი', max_digits=4, verbose_name='ფასდაკლება')),
                ('savings', models.FloatField(default=0, help_text='%', verbose_name='დანაზოგი')),
                ('quantity', models.IntegerField(verbose_name='აქციების რაოდენობა')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='აქცის დაწყების თარიღი')),
                ('end_date', models.DateField(default=datetime.datetime(2021, 4, 26, 17, 32, 43, 142971, tzinfo=utc), verbose_name='აქციის დასრულების თარიღი')),
                ('delivery', models.BooleanField(default=False, verbose_name='მიტანის სერვისი')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN კოდი')),
                ('cashback', models.FloatField(default=0, help_text='%', verbose_name='ქეშბექი')),
                ('cover', models.PositiveSmallIntegerField(choices=[(1, 'მაგარი'), (2, 'რბილი'), (3, 'სუპერი'), (4, 'მაგარი + სუპერი')])),
                ('number_of_pages', models.PositiveIntegerField(default=0, verbose_name='გვერდების რაოდენობა')),
                ('language', models.CharField(max_length=100, verbose_name='ენა')),
                ('height', models.FloatField(default=0, help_text='სმ', verbose_name='სიმაღლე')),
                ('width', models.FloatField(default=0, help_text='სმ', verbose_name='სიგანე')),
                ('description', django_editorjs_fields.fields.EditorJsTextField(verbose_name='აღწერა')),
                ('conditions', django_editorjs_fields.fields.EditorJsTextField(verbose_name='აქციის პირობები')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
