# Generated by Django 3.2 on 2021-04-14 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210414_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 20, 34, 51, 284148, tzinfo=utc), verbose_name='აქციის დასრულების თარიღი'),
        ),
    ]
