# Generated by Django 3.2 on 2021-04-15 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210415_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 15, 9, 40, 528681), verbose_name='აქციის დასრულების თარიღი'),
        ),
    ]
